blank_issues_enabled: false
contact_links:
  - name: Blackstorm Support
    url: https://t.me/BlackStormSupport
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://t.me/BlackStormSupport
    about: Basic documentation for setting up.
